In [2]:
import numpy as np
import scipy.sparse
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.model_selection import GridSearchCV, cross_val_score
from sklearn.linear_model import LogisticRegression

## Load Traning Input

In [4]:
X = scipy.sparse.load_npz("training_input.npz")
y = np.load("training_labels.npy", allow_pickle = True)

## Setup of Training

In [23]:
folds = 5

In [5]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=42)

## Naive Bayes

In [ ]:
p_grid = {}

In [6]:
from sklearn.naive_bayes import MultinomialNB
nb = MultinomialNB()
nb.fit(X_train, y_train)
y_pred = nb.predict(X_test)
from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test, y_pred))
from sklearn.metrics import accuracy_score
accuracy_score(y_test, y_pred, normalize=True)

[[5602  293]
 [ 346 4984]]


0.9430734966592428

## Logistic Regression

In [45]:
p_grid = {"C": np.logspace(-3,3,7), "penalty": ["none", "l2"]}

In [35]:

clf = LogisticRegression().fit(X_train, y_train)
y_pred = clf.predict(X_test)
print(confusion_matrix(y_test, y_pred))
accuracy_score(y_test, y_pred, normalize=True)

[[3614 2281]
 [ 785 4545]]


0.7268596881959911

In [49]:
estimator = LogisticRegression()
estimator_gs = GridSearchCV(estimator, p_grid, scoring="accuracy", cv=folds, n_jobs=-1)

accuracy_cv = cross_val_score(estimator_gs, X, y, cv=folds, scoring="accuracy")
print(accuracy_cv)

c:\Users\nicla\anaconda3\envs\classification\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
c:\Users\nicla\anaconda3\envs\classification\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_

[0.98641425 0.98641425 0.98463252 0.99008798 0.99086758]


c:\Users\nicla\anaconda3\envs\classification\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


[0.6922049  0.69888641 0.74487751 0.72157256 0.76311393]


In [36]:
np.argmax(clf.coef_[0])

1

## Support Vector Machines

Normalize inputs

In [50]:
estimator = SVC(kernel="rbf")
estimator.fit(X, y)
y_pred = clf.predict(X_test)
print(confusion_matrix(y_test, y_pred))
accuracy_score(y_test, y_pred, normalize=True)

In [42]:
estimator = SVC(kernel="rbf")
p_grid = {"C": [1, 10, 100, 100], "gamma": [.001, .01, .1, 1]}

estimator_gs = GridSearchCV(estimator, p_grid, scoring="accuracy", cv=folds, n_jobs=-1)

accuracy_cv = cross_val_score(estimator_gs, X, y, cv=folds, scoring="accuracy")

print(accuracy_cv)

KeyboardInterrupt: 